server:
  port: 8081

spring:
  application:
    name: test1-service

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
