server:
  port: 8081

spring:
  application:
    name: test1-service

# OpenTelemetry Configuration
otel:
  service:
    name: test1-service
  exporter:
    otlp:
      endpoint: http://localhost:4317
  traces:
    exporter: otlp

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
