server:
  port: 8082

spring:
  application:
    name: test2-service

# OpenTelemetry Configuration
otel:
  service:
    name: test2-service
  exporter:
    otlp:
      endpoint: http://localhost:4317
  traces:
    exporter: otlp

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
